---
-   name: Create agent user
    user:
        name: jenkins
        password: '!'
        groups:
            - docker
        state: present

-   name: Install software
    apt:
        name:
            - git
            - make
            - gettext-base
            - jq
        state: present
        update_cache: yes
