---
-   name: Add Certbot hook
    lineinfile:
        path: /etc/letsencrypt/cli.ini
        line: "post-hook = /bin/sh -c 'cd /home/deploy/jenkins && docker compose restart nginx'"
        search_string: 'post-hook'
